version: '3'
services:
    uvdesk:
        image: uvdesk1:latest
        tty: true
        depends_on:
            - db
        ports:
            - 9000:80
    db:
        image: mysql:5.7
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: uvdesk_db
            MYSQL_USER: uvdeskUser
            MYSQL_PASSWORD: uvdeskPass
        ports:
            - "9906:3306"
